#!/bin/sh
# This is the driver for the automated test suite.
# It checks syntax of the mode files, then runs a function test.

if vim -e -c 'source syntax-check.vim' 2>&1 | grep -q 'Error' ; then
  echo 'Syntax error.'
  exit 1
else
  echo 'Syntax passed.'
fi

echo 'Functional test results (Warnings about non-terminals are expected):'
yes ':q' | vim -c 'source function-check.vim' 2>&1 > ,err
tr '\033' 'E' < ,err
if grep -q 'Test failure' < ,err ; then
  echo
  echo 'Test failure!'
  exit 1
fi

# All okay
echo
echo
echo "Tests passed."
